# docker-compose.yml
version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: santas-dynamodb
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -inMemory -sharedDb'
